name: Build Boundaries

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install requests

      - run: python script/fetch_grid.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/boundaries.json

          git diff --cached --quiet || (
            git commit -m "Update boundaries"
            git push
          )
