name: Update Weather Data

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:      # manual run button

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run weather script
        run: python script/fetch_weather.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/weather.json
          git commit -m "Update weather data" || echo "No changes"
          git push
